package ebd.globalUtils.breakingCurveType;

public enum BreakingCurveType {
    C30_CURVE,
    NORMAL_INTERVENTION_CURVE,
    INDICATION_CURVE,
    PERMITTED_SPEED,
    WARNING_CURVE,
    SERVICE_INTERVENTION_CURVE_1,
    SERVICE_INTERVENTION_CURVE_2,
    EMERGENCY_INTERVENTION_CURVE,
}
